require: rubocop-rails

AllCops:
  Exclude:
    - 'coverage/**/**'
    - 'bin/**/**'
    - 'config/**/**'
    - 'lib/**/**'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  CountRepeatedAttributes: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'db/schema.rb'

Lint/MissingSuper:
  Exclude:
    - 'app/services/**/**'