require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  Exclude:
    - 'coverage/**/**'
    - 'bin/**/**'
    - 'config/**/**'
    - 'lib/**/**'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  CountRepeatedAttributes: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'db/schema.rb'

Lint/MissingSuper:
  Exclude:
    - 'app/services/**/**'

RSpec/ImplicitSubject:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/VariableName:
  AllowedPatterns:
    - ^Authorization
  Include:
    - 'spec/integration/**/**'