require: rubocop-rails

AllCops:
  Exclude:
    - 'coverage/**/**'
    - 'bin/**/**'
    - 'config/**/**'
    - 'lib/**/**'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Metrics/AbcSize:
  CountRepeatedAttributes: false

Lint/MissingSuper:
  Exclude:
    - 'app/services/**/**'