---
swagger: '2.0'
info:
  title: Railway-API
  version: v1
  description: Railway-API documentation
paths:
  "/api/v1/carriage_types":
    get:
      summary: Retrieves all carriage types. By necr0me
      tags:
      - Carriage types
      produces:
      - application/json
      security:
      - Bearer: {}
      responses:
        '200':
          description: Carriage types found
          examples:
            application/json:
              carriage_types:
              - id: 6001
                name: Rob Banks
                description: Jacobson-Weissnat
                capacity: 8
                created_at: '2023-02-15T21:05:45.584Z'
                updated_at: '2023-02-15T21:05:45.584Z'
              - id: 6002
                name: Dan Deline
                description: Hudson, Murphy and Kohler
                capacity: 8
                created_at: '2023-02-15T21:05:45.588Z'
                updated_at: '2023-02-15T21:05:45.588Z'
              - id: 6003
                name: Polly Dent
                description: Funk, Oberbrunner and Macejkovic
                capacity: 8
                created_at: '2023-02-15T21:05:45.590Z'
                updated_at: '2023-02-15T21:05:45.590Z'
        '401':
          description: You are unauthorized
          examples:
            application/json:
              message: You're not logged in
              errors:
              - Nil JSON web token
        '403':
          description: You are forbidden to perform this action
          examples:
            application/json:
              message: You are not allowed to do this action
    post:
      summary: Creates new carriage type. By necr0me
      tags:
      - Carriage types
      consumes:
      - application/json
      parameters:
      - name: params
        in: body
        schema:
          type: object
          properties:
            name:
              type: string
            description:
              type: string
            capacity:
              type: integer
          require:
          - name
          - capacity
          - description
      produces:
      - application/json
      security:
      - Bearer: {}
      responses:
        '201':
          description: Carriage type successfully created
          examples:
            application/json:
              message: Carriage type successfully created
              carriage_type:
                id: 6004
                name: Clara Nett
                description: Murphy Inc
                capacity: 8
                created_at: '2023-02-15T21:05:45.662Z'
                updated_at: '2023-02-15T21:05:45.662Z'
        '401':
          description: You are unauthorized
          examples:
            application/json:
              message: You're not logged in
              errors:
              - Nil JSON web token
        '403':
          description: You are forbiden to perform this action
          examples:
            application/json:
              message: You are not allowed to do this action
        '422':
          description: Error occurred during carriage type create
          examples:
            application/json:
              message: Something went wrong
              errors:
              - Name is too short (minimum is 3 characters)
              - Capacity must be greater than or equal to 0
  "/api/v1/carriage_types/{carriage_type_id}":
    put:
      summary: Updates carriage type. By necr0me
      tags:
      - Carriage types
      consumes:
      - application/json
      parameters:
      - name: carriage_type_id
        in: path
        type: string
        required: true
        description: Id of carriage type that you want to update
      - name: params
        in: body
        schema:
          type: object
          properties:
            name:
              type: string
            description:
              type: string
            capacity:
              type: integer
          require:
          - name
          - capacity
          - description
      produces:
      - application/json
      security:
      - Bearer: {}
      responses:
        '200':
          description: Carriage type successfully updated
          examples:
            application/json:
              message: Carriage type successfully updated
              carriage_type:
                name: New name
                description: New description
                capacity: 4
                id: 6006
                created_at: '2023-02-15T21:05:45.697Z'
                updated_at: '2023-02-15T21:05:45.720Z'
        '401':
          description: You are unauthorized
          examples:
            application/json:
              message: You're not logged in
              errors:
              - Nil JSON web token
        '403':
          description: You are forbidden to perform this action
          examples:
            application/json:
              message: You are not allowed to do this action
        '404':
          description: Carriage type not found
          examples:
            application/json:
              message: Couldn't find CarriageType with 'id'=-1
        '422':
          description: Error occurred during carriage type update
          examples:
            application/json:
              message: Something went wrong
              errors:
              - Can't update carriage type capacity that has any carriages
    delete:
      summary: Deletes carriage type. By necr0me
      tags:
      - Carriage types
      parameters:
      - name: carriage_type_id
        in: path
        type: string
        required: true
        description: Id of carriage type that you want to destroy
      produces:
      - application/json
      security:
      - Bearer: {}
      responses:
        '204':
          description: Carriage type successfully destroyed
        '401':
          description: You are unauthorized
          examples:
            application/json:
              message: You're not logged in
              errors:
              - Nil JSON web token
        '403':
          description: You are forbidden to perform this action
          examples:
            application/json:
              message: You are not allowed to do this action
        '404':
          description: Carriage type not found
          examples:
            application/json:
              message: Couldn't find CarriageType with 'id'=-1
        '422':
          description: Error occurred during carriage type destroy
          examples:
            application/json:
              message: Something went wrong
              errors:
              - Can't destroy carriage type that has any carriages
  "/api/v1/routes":
    post:
      summary: Creates empty route. By necr0me
      tags:
      - Routes
      produces:
      - application/json
      security:
      - Bearer: {}
      responses:
        '201':
          description: Route successfully created
          examples:
            application/json:
              message: Route was created
              route:
                id: 3240
                created_at: '2023-02-15T21:05:45.889Z'
                updated_at: '2023-02-15T21:05:45.889Z'
        '401':
          description: You are unauthorized
          examples:
            application/json:
              message: You're not logged in
              errors:
              - Nil JSON web token
        '403':
          description: You are forbidden to perform this action
          examples:
            application/json:
              message: You are not allowed to do this action
        '422':
          description: Error occurred during route creation
          examples:
            application/json:
              message: Something went wrong
              errors:
              - Error message
  "/api/v1/routes/{route_id}":
    get:
      summary: Find concrete route. By necr0me
      tags:
      - Routes
      parameters:
      - name: route_id
        in: path
        type: string
        required: true
        description: Id of route
      produces:
      - application/json
      responses:
        '200':
          description: Route found
          examples:
            application/json:
              route:
                id: 3243
                created_at: '2023-02-15T21:05:45.928Z'
                updated_at: '2023-02-15T21:05:45.928Z'
              stations:
              - id: 9234
                name: Mogilev
                created_at: '2023-02-15T21:05:45.940Z'
                updated_at: '2023-02-15T21:05:45.940Z'
              - id: 9235
                name: Mosty
                created_at: '2023-02-15T21:05:45.944Z'
                updated_at: '2023-02-15T21:05:45.944Z'
              - id: 9236
                name: Hrodna
                created_at: '2023-02-15T21:05:45.948Z'
                updated_at: '2023-02-15T21:05:45.948Z'
        '404':
          description: Route not found
          examples:
            application/json:
              message: Couldn't find Route with 'id'=-1
    delete:
      summary: Delete concrete route. By necr0me
      tags:
      - Routes
      parameters:
      - name: route_id
        in: path
        type: string
        required: true
        description: Id of route
      produces:
      - application/json
      security:
      - Bearer: {}
      responses:
        '204':
          description: Route successfully destroyed
        '401':
          description: You are unauthorized
          examples:
            application/json:
              message: You're not logged in
              errors:
              - Nil JSON web token
        '403':
          description: You are forbidden to perform this action
          examples:
            application/json:
              message: You are not allowed to do this action
        '404':
          description: Route not found
          examples:
            application/json:
              message: Couldn't find Route with 'id'=-1
        '422':
          description: Error occurred during route destroying
          examples:
            application/json:
              message: Something went wrong
              errors:
              - Error message
  "/api/v1/routes/{route_id}/add_station":
    post:
      summary: Add existing station to existing route. By necr0me
      tags:
      - Routes
      consumes:
      - application/json
      parameters:
      - name: route_id
        type: integer
        in: path
        required: true
        description: Id of route which to you want add station
      - name: params
        in: body
        schema:
          type: object
          properties:
            station_id:
              type: string
          required: station_id
      produces:
      - application/json
      security:
      - Bearer: {}
      responses:
        '201':
          description: Station successfully added to route
          examples:
            application/json:
              message: Station was successfully added to route
              station:
                id: 9246
                name: Melbourne
                created_at: '2023-02-15T21:05:46.175Z'
                updated_at: '2023-02-15T21:05:46.175Z'
        '401':
          description: You are unauthorized
          examples:
            application/json:
              message: You're not logged in
              errors:
              - Nil JSON web token
        '403':
          description: You are forbidden to perform this action
          examples:
            application/json:
              message: You are not allowed to do this action
        '404':
          description: Route not found
          examples:
            application/json:
              message: Couldn't find Route with 'id'=-1
        '422':
          description: Station does not exist
          examples:
            application/json:
              message: Something went wrong
              errors:
              - 'Validation failed: Station must exist'
  "/api/v1/routes/{route_id}/remove_station/{station_id}":
    delete:
      summary: Remove station from route. By necr0me
      tags:
      - Routes
      parameters:
      - name: route_id
        in: path
        type: string
        required: true
        description: Id of route where from station removing
      - name: station_id
        in: path
        type: string
        required: true
        description: Id of station that removing from route
      produces:
      - application/json
      security:
      - Bearer: {}
      responses:
        '200':
          description: Successfully remove station from route
          examples:
            application/json:
              message: Station was successfully removed from route
        '401':
          description: You are unauthorized
          examples:
            application/json:
              message: You're not logged in
              errors:
              - Nil JSON web token
        '403':
          description: You are forbidden to perform this action
          examples:
            application/json:
              message: You are not allowed to do this action
        '404':
          description: Route not found
          examples:
            application/json:
              message: Couldn't find Route with 'id'=-1
        '422':
          description: Station already not in route
          examples:
            application/json:
              message: Something went wrong
              errors:
              - Couldn't find StationOrderNumber with [WHERE "station_order_numbers"."route_id"
                = $1 AND "station_order_numbers"."station_id" = $2]
  "/api/v1/stations":
    get:
      summary: Gets all stations. By necr0me
      tags:
      - Stations
      produces:
      - application/json
      parameters:
      - name: station
        in: query
        type: string
        required: false
        description: Name of station or first N letters of station name
      responses:
        '200':
          description: Stations found (From query "?station=Mo")
          examples:
            application/json:
            - id: 9275
              name: Mogilev
              created_at: '2023-02-15T21:05:46.564Z'
              updated_at: '2023-02-15T21:05:46.564Z'
            - id: 9276
              name: Mosty
              created_at: '2023-02-15T21:05:46.567Z'
              updated_at: '2023-02-15T21:05:46.567Z'
    post:
      summary: Create a new station. By necr0me
      tags:
      - Stations
      consumes:
      - application/json
      parameters:
      - name: params
        in: body
        schema:
          type: object
          properties:
            name:
              type: string
          required: name
      produces:
      - application/json
      security:
      - Bearer: {}
      responses:
        '201':
          description: Station created
          examples:
            application/json:
              station:
                id: 9278
                name: Melbourne
                created_at: '2023-02-15T21:05:46.595Z'
                updated_at: '2023-02-15T21:05:46.595Z'
        '401':
          description: You are unauthorized
          examples:
            application/json:
              message: You're not logged in
              errors:
              - Nil JSON web token
        '403':
          description: You are forbidden to perform this action
          examples:
            application/json:
              message: You are not allowed to do this action
        '422':
          description: Errors during station creation
          examples:
            application/json:
              message: Something went wrong
              errors:
              - Name is too short (minimum is 2 characters)
  "/api/v1/stations/{id}":
    get:
      summary: Get concrete station. By necr0me
      tags:
      - Stations
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        type: string
        required: true
        description: Id of station
      responses:
        '200':
          description: Station was found
          examples:
            application/json:
              id: 9280
              name: Melbourne
              created_at: '2023-02-15T21:05:46.629Z'
              updated_at: '2023-02-15T21:05:46.629Z'
        '404':
          description: Station not found
          examples:
            application/json:
              message: Couldn't find Station with 'id'=-1
    put:
      summary: Update concrete station. By necr0me
      tags:
      - Stations
      consumes:
      - application/json
      parameters:
      - name: params
        in: body
        schema:
          type: object
          properties:
            name:
              type: string
          required: name
      - name: id
        in: path
        type: string
        required: true
        description: Id of station
      produces:
      - application/json
      security:
      - Bearer: {}
      responses:
        '200':
          description: Station updated
          examples:
            application/json:
              station:
                name: New name
                id: 9281
                created_at: '2023-02-15T21:05:46.641Z'
                updated_at: '2023-02-15T21:05:46.652Z'
        '401':
          description: You are unauthorized
          examples:
            application/json:
              message: You're not logged in
              errors:
              - Nil JSON web token
        '403':
          description: You are forbidden to perform this action
          examples:
            application/json:
              message: You are not allowed to do this action
        '404':
          description: Station not found
          examples:
            application/json:
              message: Couldn't find Station with 'id'=-1
        '422':
          description: Something went wrong during station update
          examples:
            application/json:
              message: Something went wrong
              errors:
              - Name can't be blank
              - Name is too short (minimum is 2 characters)
    delete:
      summary: Delete concrete station. By necr0me
      tags:
      - Stations
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        type: string
        required: true
        description: Id of station
      security:
      - Bearer: {}
      responses:
        '204':
          description: Successfully destroyed station
        '401':
          description: You are unauthorized
          examples:
            application/json:
              message: You're not logged in
              errors:
              - Nil JSON web token
        '403':
          description: You are forbidden to perform this action
          examples:
            application/json:
              message: You are not allowed to do this action
        '404':
          description: Station not found
          examples:
            application/json:
              message: Couldn't find Station with 'id'=-1
        '422':
          description: Something went wrong during station destroying
          examples:
            application/json:
              message: Something went wrong
              errors:
              - Error message
securityDefinitions:
  Bearer:
    description: Authorization header (JWT-token)
    type: apiKey
    name: Authorization
    in: header
servers:
- url: http://{defaultHost}/
  variables:
    defaultHost:
      default: localhost:3000
